# SPDX-FileCopyrightText: 2024 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: Unlicense

name: build

on:
  push:
    branches: [ master, main, develop ]
  schedule:
    # Every day at 02:21
    - cron: "21 2 * * *"

jobs:
  update_lov_dump:
    name: Update LOV dump repo on codeberg (potentially)
    runs-on: ubuntu-latest
    steps:
      - name: "Install required tools"
        run: |
          sudo apt-get install -y curl gzip

      - name: "Create the build directory"
        run: |
          mkdir -p "build"

      - name: "Write key to temp file"
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          SSH_PRIVATE_KEY: ${{secrets.CODEBERG_ACCESS_PRIVATE_KEY}}
        run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan codeberg.org >> /home/runner/.ssh/known_hosts
          touch "/home/runner/.ssh/id_codeberg_org"
          chmod 600 "/home/runner/.ssh/id_codeberg_org"
          echo "$SSH_PRIVATE_KEY" \
            > "/home/runner/.ssh/id_codeberg_org"
          chmod 400 "/home/runner/.ssh/id_codeberg_org"
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add /home/runner/.ssh/id_codeberg_org

      - name: Cache Repo
        id: cache-repo
        uses: actions/cache@v4
        with:
          path: build/lov-dump
          key: repo

      - name: "Clone the repo"
        if: steps.cache-repo.outputs.cache-hit != 'true'
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          cd "build"
          git \
            -c core.sshCommand="ssh -i '/home/runner/.ssh/id_codeberg_org' -o IdentitiesOnly=yes" \
            clone \
            "git@codeberg.org:elevont/lov-dump.git" \
            "lov-dump"
          git -C "lov-dump" config core.sshCommand \
            "ssh -i '/home/runner/.ssh/id_codeberg_org' -o IdentitiesOnly=yes"
          cd ..

      - name: "Update the repo"
        if: steps.cache-repo.outputs.cache-hit == 'true'
        run: |
          cd "build/lov-dump"
          git pull
          cd ..

      - name: "Download the data dump, extract and move it, and update the repo"
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          cd "build"
          curl --location --silent -O "https://lov.linkeddata.es/lov.nq.gz"
          gunzip "lov.nq.gz"
          mv "lov.nq" "lov-dump/"
          cd "lov-dump"
          git config --global user.email "actions@github.com"
          git config --global user.name "LOV-dump-updater GitHub-actions (https://github.com/elevont/lov-dump-updater)"
          git add "lov.nq"
          git commit -m "Updated data dump"
          cd ../..

      - name: "Push changes to the remote repo"
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          cd "build/lov-dump"
          git push
          cd ../..
